## Método de Jacobi

${x_i^k} = T*x_{k-1} + c$


ejercicio 1

In [16]:
import numpy as np

from math import *


In [59]:
#Definimos la matriz T
T = np.array([[0,1/3,-1/3],[-3/6,0,-2/6],[-3/7,-3/7,0]])
c = np.array([1/3,0,4/7])
x = np.array([0,0,0]) #vector de valores iniciales
erroraceptado=0.01
cm=0

In [60]:
#print("matriz de: ", T.shape)
print(T, "*", x, "+", c)
print()
#print("vector de: ", c.shape)
#print(c)
#error=1
#print()
error=1

while error>0.01:
    cm+=1
    resultado=np.dot(T,x) + c
    print("iteracion: ",cm, "resultado: ", resultado, "error: ", error)
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    
    x=resultado
    



[[ 0.          0.33333333 -0.33333333]
 [-0.5         0.         -0.33333333]
 [-0.42857143 -0.42857143  0.        ]] * [0 0 0] + [0.33333333 0.         0.57142857]

iteracion:  1 resultado:  [0.33333333 0.         0.57142857] error:  1
iteracion:  2 resultado:  [ 0.14285714 -0.35714286  0.42857143] error:  1.0
iteracion:  3 resultado:  [ 0.07142857 -0.21428571  0.66326531] error:  0.8333333333333333
iteracion:  4 resultado:  [ 0.04081633 -0.25680272  0.63265306] error:  0.35384615384615387
iteracion:  5 resultado:  [ 0.03684807 -0.23129252  0.66399417] error:  0.06720430107526885
iteracion:  6 resultado:  [ 0.03490444 -0.23975543  0.6547619 ] error:  0.047200878155872754
iteracion:  7 resultado:  [ 0.03516089 -0.23570619  0.65922185] error:  0.014100185528757097


ejercicio 2

In [47]:
#Definimos la matriz T
T = np.array([[0,1/10,0],[1/10,0,2/10],[0,2/10,0]])
c = np.array([9/10,7/10,6/10])
x = np.array([0,0,0]) #vector de valores iniciales
erroraceptado=0.01
cm=0

In [48]:
print("matriz de: ", T.shape)
print(T)
print()
print("vector de: ", c.shape)
print(c)
error=1
print()
error=1

while error>0.01:
    cm+=1
    resultado=np.dot(T,x) + c
    print("iteracion: ",cm, "resultado: ", resultado, "error: ", error)
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    
    x=resultado

matriz de:  (3, 3)
[[0.  0.1 0. ]
 [0.1 0.  0.2]
 [0.  0.2 0. ]]

vector de:  (3,)
[0.9 0.7 0.6]

iteracion:  1 resultado:  [0.9 0.7 0.6] error:  1
iteracion:  2 resultado:  [0.97 0.91 0.74] error:  1.0
iteracion:  3 resultado:  [0.991 0.945 0.782] error:  0.21649484536082472
iteracion:  4 resultado:  [0.9945 0.9555 0.789 ] error:  0.04238143289606462
iteracion:  5 resultado:  [0.99555 0.95725 0.7911 ] error:  0.010558069381598858


ejercicio 3

In [49]:
#Definimos la matriz T
T = np.array([[0, -5/10, 0, 0],[-5/10, 0, 4/10, 0],[0, 4/8, 0, 1/8], [0, 0, 1/5, 0]])
c = np.array([3/5, 5/2, -11/8, -11/5])
x = np.array([0,0,0,0]) #vector de valores iniciales
erroraceptado=0.01
cm=0

In [50]:
print("matriz de: ", T.shape)
print(T)
print()
print("vector de: ", c.shape)
print(c)
error=1
print()
while error>0.01:
    cm+=1
    resultado=np.dot(T,x) + c
    print("iteracion: ",cm, "resultado: ", resultado, "error: ", error)
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    
    x=resultado

matriz de:  (4, 4)
[[ 0.    -0.5    0.     0.   ]
 [-0.5    0.     0.4    0.   ]
 [ 0.     0.5    0.     0.125]
 [ 0.     0.     0.2    0.   ]]

vector de:  (4,)
[ 0.6    2.5   -1.375 -2.2  ]

iteracion:  1 resultado:  [ 0.6    2.5   -1.375 -2.2  ] error:  1
iteracion:  2 resultado:  [-0.65   1.65  -0.4   -2.475] error:  1.0
iteracion:  3 resultado:  [-0.225     2.665    -0.859375 -2.28    ] error:  0.5050505050505051
iteracion:  4 resultado:  [-0.7325    2.26875  -0.3275   -2.371875] error:  0.3808630393996248
iteracion:  5 resultado:  [-0.534375    2.73525    -0.53710938 -2.2655    ] error:  0.22424242424242416
iteracion:  6 resultado:  [-0.767625    2.55234375 -0.2905625  -2.30742188] error:  0.17055113792157936
iteracion:  7 resultado:  [-0.67617187  2.7675875  -0.38725586 -2.2581125 ] error:  0.0965962656871748
iteracion:  8 resultado:  [-0.78379375  2.68318359 -0.27347031 -2.27745117] error:  0.07777306047234278
iteracion:  9 resultado:  [-0.7415918   2.78250875 -0.3180896  -2.25

ejercicio 4

In [51]:
#Definimos la matriz T
T = np.array([[0, -1/4, 1/4, -1/4],[-1/4, 0, 1/4, 1/4],[1/5, 1/5, 0, -1/5], [-1/3, 1/3, -1/3, 0]])
c = np.array([-1/2, -1/4, 0, 1/3])
x = np.array([0,0,0,0]) #vector de valores iniciales
erroraceptado=0.01
cm=0

In [52]:
print("matriz de: ", T.shape)
print(T)
print()
print("vector de: ", c.shape)
print(c)
error=1
print()
error=1

while error>0.01:
    cm+=1
    resultado=np.dot(T,x) + c
    print("iteracion: ",cm, "resultado: ", resultado, "error: ", error)
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    
    x=resultado

matriz de:  (4, 4)
[[ 0.         -0.25        0.25       -0.25      ]
 [-0.25        0.          0.25        0.25      ]
 [ 0.2         0.2         0.         -0.2       ]
 [-0.33333333  0.33333333 -0.33333333  0.        ]]

vector de:  (4,)
[-0.5        -0.25        0.          0.33333333]

iteracion:  1 resultado:  [-0.5        -0.25        0.          0.33333333] error:  1
iteracion:  2 resultado:  [-0.52083333 -0.04166667 -0.21666667  0.41666667] error:  1.0
iteracion:  3 resultado:  [-0.64791667 -0.06979167 -0.19583333  0.56527778] error:  0.416
iteracion:  4 resultado:  [-0.67282986  0.00434028 -0.25659722  0.59131944] error:  0.22936763129689178
iteracion:  5 resultado:  [-0.71306424  0.00188802 -0.25196181  0.64458912] error:  0.11017933169913562
iteracion:  6 resultado:  [-0.72460974  0.02642289 -0.27115307  0.65563802] error:  0.07470529754296246
iteracion:  7 resultado:  [-0.73830349  0.02727367 -0.27076497  0.6740619 ] error:  0.03385942205279923
iteracion:  8 resultado:  [